# generated by datamodel-codegen:
#   filename:  MetadataStateChange.schema.json
#   timestamp: 2025-10-06T00:46:40+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Source(Enum):
    orcabus_metadatamanager = 'orcabus.metadatamanager'


class DetailType(Enum):
    MetadataStateChange = 'MetadataStateChange'


class Model(Enum):
    LIBRARY = 'LIBRARY'


class Action(Enum):
    CREATE = 'CREATE'
    UPDATE = 'UPDATE'
    DELETE = 'DELETE'


class MetadataStateChange(BaseModel):
    model: Model
    action: Action
    refId: str
    data: Dict[str, Any]


class AWSEvent(BaseModel):
    id: Optional[str] = None
    region: Optional[str] = None
    resources: Optional[List[str]] = None
    source: Source
    time: Optional[datetime] = None
    version: Optional[str] = None
    account: Optional[str] = None
    detail_type: DetailType = Field(..., alias='detail-type')
    detail: MetadataStateChange
