# Generated by Django 5.2.2 on 2025-06-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_historicallibrary_override_cycles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallibrary',
            name='workflow',
            field=models.CharField(blank=True, choices=[('clinical', 'Clinical'), ('research', 'Research'), ('qc', 'Qc'), ('control', 'Control'), ('bcl', 'Bcl'), ('manual', 'Manual'), ('germline', 'germline only')], null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='workflow',
            field=models.CharField(blank=True, choices=[('clinical', 'Clinical'), ('research', 'Research'), ('qc', 'Qc'), ('control', 'Control'), ('bcl', 'Bcl'), ('manual', 'Manual'), ('germline', 'germline only')], null=True),
        ),
    ]
