# Generated by Django 5.2.2 on 2025-09-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_historicallibrary_workflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallibrary',
            name='type',
            field=models.CharField(blank=True, choices=[('10X', 'Ten X'), ('BiModal', 'Bimodal'), ('ctDNA', 'Ct Dna'), ('ctTSO', 'Ct Tso'), ('exome', 'Exome'), ('MeDIP', 'Me Dip'), ('Metagenm', 'Metagenm'), ('MethylSeq', 'Methyl Seq'), ('TSO-DNA', 'TSO_DNA'), ('TSO-RNA', 'TSO_RNA'), ('WGS', 'Wgs'), ('WTS', 'Wts'), ('iMethyl5B', 'I Methyl 5B'), ('iMthyl5BCap', 'I Mthyl 5B Cap'), ('other', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='type',
            field=models.CharField(blank=True, choices=[('10X', 'Ten X'), ('BiModal', 'Bimodal'), ('ctDNA', 'Ct Dna'), ('ctTSO', 'Ct Tso'), ('exome', 'Exome'), ('MeDIP', 'Me Dip'), ('Metagenm', 'Metagenm'), ('MethylSeq', 'Methyl Seq'), ('TSO-DNA', 'TSO_DNA'), ('TSO-RNA', 'TSO_RNA'), ('WGS', 'Wgs'), ('WTS', 'Wts'), ('iMethyl5B', 'I Methyl 5B'), ('iMthyl5BCap', 'I Mthyl 5B Cap'), ('other', 'Other')], null=True),
        ),
    ]
