# Generated by Django 5.2.2 on 2026-05-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_historicallibrary_type_alter_library_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallibrary",
            name="request_form_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="library",
            name="request_form_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
